variables:
- group: GH
- name: R_LIBS_USER
  value: '$(Agent.BuildDirectory)/R/library'
- name: containerImage
  value: 'rocker/rstudio:latest'

pool:
  vmImage: 'ubuntu-latest'

container: $[variables['containerImage']]

steps:
- bash: |
    git push --prune https://$(ghPat)@github.com/cloudyr/$(Build.Repository.Name) +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
  displayName: 'Copy to Cloudyr'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')

- bash: |
    echo 'options(repos = "https://cloud.r-project.org")' > ~/.Rprofile
    echo ".libPaths(c('$R_LIBS_USER', .libPaths()))" >> ~/.Rprofile
    mkdir -p $(R_LIBS_USER)
  displayName: 'Setup R library directory'

- task: CacheBeta@0
  inputs:
    key: ./DESCRIPTION | "$(containerImage)"
    path: $(R_LIBS_USER)
  displayName: 'Caching packages'

- bash: |
    Rscript -e "install.packages(c('remotes', 'rcmdcheck', 'drat'))"
    Rscript -e "remotes::install_deps(dependencies=TRUE)"
  displayName: 'Installing package dependencies'

- bash: |
    Rscript -e "f <- pkgbuild::build(dest_path='$(Build.ArtifactStagingDirectory)'); rcmdcheck::rcmdcheck(f, args='--no-manual', error_on='warning', check_dir='check'); Sys.setenv(PKGBUILD_GZ=f)"
    echo '##vso[task.setvariable variable=PkgBuild_gz]$PKGBUILD_GZ'
  displayName: 'Checking package'

- bash: |
    mkdir drat
    cd drat
    git init
    git config --global push.default simple
    git remote add upstream "https://$(ghPat)@github.com/cloudyr/cloudyr.github.io.git"
    git fetch upstream
    git checkout master
    Rscript -e "drat::insertPackage('$(PkgBuild_gz)', repodir='./drat')"
    git add --all
    git commit -m "add $(PkgBuild_gz) (build $(Build.BuildId))"
  displayName: 'Update drat repo'
