trigger:
- pipeline-testing

variables:
- group: GH
- name: R_LIBS_USER
  value: '$(Agent.BuildDirectory)/R/library'

pool:
  vmImage: 'ubuntu-latest'

container: rocker/rstudio:latest

steps:
- script: |
    echo 'options(repos = "https://cloud.r-project.org")' > ~/.Rprofile
    echo ".libPaths(c('$R_LIBS_USER', .libPaths()))" >> ~/.Rprofile
    mkdir -p $(R_LIBS_USER)
  displayName: 'Setup R library directory'

- bash: |
    Rscript -e "install.packages(c('remotes', 'rcmdcheck'))"
    Rscript -e "remotes::install_deps(dependencies=TRUE)"
  displayName: 'Installing package dependencies'

- bash: |
    Rscript -e "rcmdcheck::rcmdcheck(args='--no-manual', error_on='error', check_dir='check')"
  displayName: 'Checking package'
